version: "3" 
services:
  kafka-outbound-delivery-service:
    environment:
      - ACAPY_OUTBOUND_TRANSPORT_QUEUE=${ACAPY_OUTBOUND_TRANSPORT_QUEUE}
      - ACAPY_OUTBOUND_TRANSPORT_QUEUE_PREFIX=${ACAPY_OUTBOUND_TRANSPORT_QUEUE_PREFIX}
      - DELIVERY_SERVICE_ENDPOINT_TRANSPORT=${DELIVERY_SERVICE_ENDPOINT_TRANSPORT}
      - DELIVERY_SERVICE_ENDPOINT_KEY=${DELIVERY_SERVICE_ENDPOINT_KEY}
    networks:
      - delivey_service_network
    ports:
      - ${DELIVERY_SERVICE_ENDPOINT_TRANSPORT_PORT}:${DELIVERY_SERVICE_ENDPOINT_TRANSPORT_PORT}
    build: 
      context: ..
      dockerfile: ./delivery_service/kafka/outbound/docker/Dockerfile.run
  redis-outbound-delivery-service:
    environment:
      - ACAPY_OUTBOUND_TRANSPORT_QUEUE=${ACAPY_OUTBOUND_TRANSPORT_QUEUE}
      - ACAPY_OUTBOUND_TRANSPORT_QUEUE_PREFIX=${ACAPY_OUTBOUND_TRANSPORT_QUEUE_PREFIX}
      - DELIVERY_SERVICE_ENDPOINT_TRANSPORT=${DELIVERY_SERVICE_ENDPOINT_TRANSPORT}
      - DELIVERY_SERVICE_ENDPOINT_KEY=${DELIVERY_SERVICE_ENDPOINT_KEY}
    networks:
      - delivey_service_network
    ports:
      - ${DELIVERY_SERVICE_ENDPOINT_TRANSPORT_PORT}:${DELIVERY_SERVICE_ENDPOINT_TRANSPORT_PORT}
    build:
      context: ..
      dockerfile: ./delivery_service/redis/outbound/docker/Dockerfile.run
networks:
  delivey_service_network:
    external: true
    name: ${DELIVERY_SERVICE_NETWORK_NAME}