name: Publish ACA-Py
on:
  # When running via release the tag pattern is being ignored
  # for example
  # release version: 1.0.0-rc5
  # Resulting image:
  # - aries-cloudagent-python:1.0.0-rc5
  # Expecting images:
  # - aries-cloudagent-python:py3.8-1.0.0-rc5
  # - aries-cloudagent-python:py3.9-1.0.0-rc5
  release:
    types: [released]

  # When running via workflow_dispatch only the tag is used version is ignored
  # for example
  # tag: 1.0.0-rc5-mt
  # version: 1.0.0-rc5-mvl
  # Resulting images:
  # - aries-cloudagent-python:py3.8-1.0.0-rc5-mt
  # - aries-cloudagent-python:py3.9-1.0.0-rc5-mt
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        type: string
      version:
        description: "Version label in image"
        required: true
        type: string

jobs:
  publish-image:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9']

    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Gather image info
        id: info
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "repo-owner=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT
          echo "${GITHUB_CONTEXT}"

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Image Metadata (manual)
        if: github.event_name == 'workflow_dispatch'
        id: dispatch-meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ steps.info.outputs.repo-owner }}/aries-cloudagent-python
          tags: |
            type=raw,value=py${{ matrix.python-version }}-${{ inputs.tag }}

      - name: Setup Image Metadata (release)
        if: github.event_name == 'release'
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ steps.info.outputs.repo-owner }}/aries-cloudagent-python
          tags: |
            type=semver,pattern=py${{ matrix.python-version }}-{{ version }}

      - name: Build and Push Image to ghcr.io
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: docker/Dockerfile
          tags: ${{ steps.dispatch-meta.outputs.tags || steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            python_version=${{ matrix.python-version }}
            acapy_version=${{ inputs.version || github.event.release.tag_name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
